In [1]:
pwd

'/home/owen/Lab/PichiaCLM/Model_PichiaCLM/Training/AllData'

In [2]:
import logging
import time
import os

from DataPrep_AllData import data_prep

import numpy as np
import matplotlib.pyplot as plt

#import tensorflow_datasets as tfds
import tensorflow as tf

# Import tf_text to load the ops used by the tokenizer saved model
#import tensorflow_text  # pylint: disable=unused-import
import pandas as pd
import numpy as np
import re
import seaborn as sns
import matplotlib as plt


from sklearn.model_selection import train_test_split


from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Model,  Sequential
from tensorflow.keras.layers import LSTM, GRU, Bidirectional, Dropout, Input, TimeDistributed, Dense, Activation, RepeatVector, Embedding, Concatenate
import tensorflow.keras.layers as layers
from tensorflow.keras.layers import Attention
from tensorflow.keras.optimizers import Adam, Adagrad
from keras.losses import sparse_categorical_crossentropy
logging.getLogger('tensorflow').setLevel(logging.ERROR)  # suppress warnings
import random

I0000 00:00:1774825981.292691 1258240 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
N_organisms = 5
Data_dict = {0: pd.read_csv('CBS7435.csv'),  1:pd.read_csv('GS115_ext.csv'), 
           2:pd.read_csv('Kpastoris_WT.csv'),  3:  pd.read_csv('Kphaffi_GS115_int.csv'), 
            4: pd.read_csv('Kphaffi_WT.csv')}

In [4]:
AA_tr,  Cds_tr, AA_ts, Cds_ts = data_prep(N_organisms, Data_dict)

Data_prepped = {'AA_tr': AA_tr, 
               'AA_ts': AA_ts, 
                'Cds_tr': Cds_tr,
                'Cds_ts':Cds_ts}

import pickle
with open('Pichia_All_2Target.pkl', 'wb') as output:
    # Pickle dictionary using protocol 0.
    pickle.dump(Data_prepped, output)

In [3]:
import pandas as pd

# Load the pickle file into a DataFrame
df = pd.read_pickle('Pichia_All_2Target.pkl')
print(df['Cds_ts'].shape)
print(df['AA_tr'])


(64, 1000)
[[24  1 23 ...  0  0  0]
 [24  1 23 ...  0  0  0]
 [24  1 23 ...  0  0  0]
 ...
 [24 11 10 ...  0  0  0]
 [24 11 17 ...  0  0  0]
 [24 11 17 ...  0  0  0]]
